providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
nixOverlays = []
aptPkgs = ["curl"]

[phases.install]
cmds = [
  "npm install -g pnpm@10",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
